minimum_pre_commit_version: "4.0.0"
default_install_hook_types: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --locked ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: uv run --locked ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        files: '(^Cargo\.toml$|^rust-toolchain\.toml$|\.rs$)'
        pass_filenames: false
      - id: uv-lock
        name: uv lock
        entry: uv lock --check
        language: system
        files: '(^|/)(pyproject\.toml|uv\.lock)$'
        pass_filenames: false
