"""Generate a conservative notice inventory from the locked Rust dependency graph.

Includes build/test/target-specific dependencies as well as runtime dependencies.
Upstream license files omitted from crate archives are retained in licenses/upstream.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PREFIXES = ("LICENSE", "COPYING", "NOTICE", "COPYRIGHT")


def main() -> None:
    data = json.loads(
        subprocess.check_output(
            [str(ROOT / "scripts/cargo.sh"), "metadata", "--locked", "--format-version", "1"],
            cwd=ROOT,
            text=True,
        )
    )
    parts = [
        "Third-party notices for qwen-mm\n",
        "Generated by scripts/third_party_licenses.py from Cargo.lock. Includes a conservative "
        "superset of runtime, build, test, and platform-specific dependencies.\n"
        "SPDX expressions describe upstream licensing choices; inclusion does not relicense "
        "third-party code. Unmodified source is available from the listed crate and repository URLs.\n",
    ]
    for package in sorted(data["packages"], key=lambda p: (p["name"], p["version"])):
        if package["name"].startswith("qwen-mm"):
            continue
        directory = Path(package["manifest_path"]).parent
        sources = [
            p for p in directory.iterdir() if p.is_file() and p.name.upper().startswith(PREFIXES)
        ]
        override = ROOT / "licenses/upstream" / package["name"]
        if override.exists():
            sources += [
                p for p in override.iterdir() if p.is_file() and p.name.upper().startswith(PREFIXES)
            ]
        parts += [
            "\n" + "=" * 78 + "\n",
            f"{package['name']} {package['version']}\n",
            f"Declared license: {package['license']}\n",
            f"Authors (upstream metadata): {', '.join(package['authors']) or 'see upstream source'}\n",
            f"Source: https://crates.io/crates/{package['name']}/{package['version']}\n",
            f"Repository: {package.get('repository') or 'see source archive'}\n",
        ]
        if package["name"] == "fxhash":
            parts.append("Copyright 2015 The Rust Project Developers.\n")
        if not sources:
            expression = package.get("license") or ""
            if "Apache-2.0" in expression:
                sources = [ROOT / "LICENSE"]
            elif expression == "MIT":
                sources = [ROOT / "licenses/MIT.txt"]
            else:
                raise RuntimeError(f"Missing license text for {package['name']}")
            parts.append(
                "The crate omits a license file; standard text for its declared license follows.\n"
            )
        seen = set()
        for source in sorted(sources):
            text = source.read_text(errors="strict")
            if text in seen:
                continue
            seen.add(text)
            if source == ROOT / "licenses/MIT.txt":
                text = "\n".join(
                    line for line in text.splitlines() if not line.startswith("Copyright (c)")
                )
            parts += [f"\n--- {source.name} ---\n", text.rstrip() + "\n"]
    (ROOT / "THIRD_PARTY_LICENSES.txt").write_text("".join(parts))


if __name__ == "__main__":
    main()
